### ISSUE TITLE
Testing Login

### ISSUE THREAD

**Issue by reubenbrown13** [redound/phalcon-rest-boilerplate#2]
I can get the users/authorize function to work, but every time I try to use users/login/ I get: "error":{"code":3007,"status":404,"developer":null,"message":"Auth: No username present"}}.

I have tried using both get and post methods to allow for the login to work.  the user string that I am using is: /users/login?bearer=1&username=test&password=test

I am running this on an nginx server and I have the url rewriting setup.  Here is what the server is getting: rewritten data: "/index.php", args: "_url=/users/login&bearer=1&username=test&password=test"

**Comment by andevsoftware** [comment]
@reubenbrown13  Because of poor separation of concerns in the [phalcon-rest](https://github.com/olivierandriessen/phalcon-rest) repo as well as the [phalcon-rest-boilerplate](https://github.com/olivierandriessen/phalcon-rest-boilerplate) I've been refactoring the library to make it more flexible, so each class of the library can be replaced with a class of your own. While doing this I've also changed the way authentication works.

When you checkout the latest develop branch the authentication flow is as followed:

POST - /users/authentication/username
You need to send the Basic Authentication header along

```
Authorization: Basic b2xpdmllcjp0ZXN0MjEz
```

The string after Basic is basically 'username:passsword' base64 encoded.

The response will be something like:

``` json
{
  "data": {
    "AuthToken": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJBcHBsaWNhdGlvbiIsInN1YiI6eyJpZCI6IjE1IiwibmFtZSI6Ik9saXZpZXIgQW5kcmllc3NlbiIsImVtYWlsIjoib2xpdmllci5hbmRyaWVzc2VuQGdtYWlsLmNvbSIsImFjdGl2ZSI6IjEiLCJtYWlsVG9rZW4iOm51bGwsImNyZWF0ZWRBdCI6IjIwMTUtMDYtMDkgMDc6MTA6NDgiLCJ1cGRhdGVkQXQiOiIyMDE1LTA2LTA5IDA3OjExOjU4In0sImlhdCI6MTQzMzg0MDg1NCwiZXhwIjoxNDM0NDQ1NjU0fQ.OqeGjU-HMOna3vQKHREoqNYf1Dm0kgHtnlh4C2XgO9w",
    "Expires": 1434445654
  }
}
```

Then for each request you do you can use the AuthToken (JsonWebToken) to authorize each private request.

As follows:
GET /products
You need to send the Basic Authentication header along with the AuthToken instead of the encoded username and password.

```
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJBcHBsaWNhdGlvbiIsInN1YiI6eyJpZCI6IjE1IiwibmFtZSI6Ik9saXZpZXIgQW5kcmllc3NlbiIsImVtYWlsIjoib2xpdmllci5hbmRyaWVzc2VuQGdtYWlsLmNvbSIsImFjdGl2ZSI6IjEiLCJtYWlsVG9rZW4iOm51bGwsImNyZWF0ZWRBdCI6IjIwMTUtMDYtMDkgMDc6MTA6NDgiLCJ1cGRhdGVkQXQiOiIyMDE1LTA2LTA5IDA3OjExOjU4In0sImlhdCI6MTQzMzg0MDg1NCwiZXhwIjoxNDM0NDQ1NjU0fQ.OqeGjU-HMOna3vQKHREoqNYf1Dm0kgHtnlh4C2XgO9w
```

Alternatively you can pass it as a get parameter on each request like so:

```
GET /products?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJBcHBsaWNhdGlvbiIsInN1YiI6eyJpZCI6IjE1IiwibmFtZSI6Ik9saXZpZXIgQW5kcmllc3NlbiIsImVtYWlsIjoib2xpdmllci5hbmRyaWVzc2VuQGdtYWlsLmNvbSIsImFjdGl2ZSI6IjEiLCJtYWlsVG9rZW4iOm51bGwsImNyZWF0ZWRBdCI6IjIwMTUtMDYtMDkgMDc6MTA6NDgiLCJ1cGRhdGVkQXQiOiIyMDE1LTA2LTA5IDA3OjExOjU4In0sImlhdCI6MTQzMzg0MDg1NCwiZXhwIjoxNDM0NDQ1NjU0fQ.OqeGjU-HMOna3vQKHREoqNYf1Dm0kgHtnlh4C2XgO9w
```

I'll better document this in the future.

When you have feedback besides your question or if this doesn't answer your question,
Make sure to let me know.
