### ISSUE TITLE
Question: Best way to handle file up- and downloads?

### ISSUE THREAD

**Issue by phil-schreiber** [redound/phalcon-rest-boilerplate#33]
Hi,

is there an implemented way to handle flat file up- and downloads? I see that firebase allows for the query param ?download= to transform the response into an file download. Is there any designated way to implement that behaviour? The boilerplate works with a photo example unfortunately without actually handling the corresponding image files. I'm having a little trouble finding a good way to implement handling of flat files without deviating from the well structured ways too much.

Would be grateful for any tips.

Thank you
Phil

**Comment by andevsoftware** [comment]
@phil-schreiber Thanks for reaching out. As of yet there isn't any designated way to implement this behaviour using phalcon-rest. In the future I hope to make it more convenient to down/upload files by adding some basic abstractions to the phalcon-rest library. Personally, depending on the actual case, I would see the files as a separate resource (write files to disk and store metadata in own table), thus processing the file uploads at a separate endpoint and return references that I would then use to store alongside the resource (basically photo hasOne asset). Then you could also make a separate endpoint that you can call with this reference in order to obtain the files like you said (eg ?download).

You might also want to look at http://docs.phalconphp.com/en/latest/api/Phalcon_Http_Request_File.html

**Comment by phil-schreiber** [comment]
Thanks for getting back to me.

I'm just handling the files in a controller on afterHandleCreate hook. This saves a few requests.
