### ISSUE TITLE
AuthToken Question

### ISSUE THREAD

**Issue by reubenbrown13** [redound/phalcon-rest-boilerplate#5]
I greatly appreciate all your attention and help.  Things are working better however now that I get my authtoken back, every time I try to pass it in the header I still get an "Unauthorized" error.  I am using php-fpm and nginx as the server and I think I have everything setup properly there, especially since the INVO app is also running on that server and works just fine.  Is the header for the auth supposed to be an array that resembles: ["AuthToken: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9..............","Expires: 1434815740","Content-Type: application/json","Content-Length: 100"] ?  It seems like the things I keep missing are simple, but without documentation, it is hard to jump in on this and get it figured out.  Thanks again for the help.

**Comment by andevsoftware** [comment]
No problem at all. Although your questions already give me a certain insight what's necessary to document, if things initially were unclear that you were able to solve yourself just let me know, for me that's great feedback. Due to lack of time the documentation is still on my todo-list.

To answer your question, simply passing the AuthToken as an Authorization header will do the trick.

The process is similar to the initial authentication.

Initial authentication process:
_/users/authenticate/username_

```
Authorization: Basic {{Base64encodedusernamepassword}}
```

The authorization process:
_/any/path/that/needs/authorization_

```
Authorization: Basic {{TheAuthTokenReceivedFromTheAuthenticationProcess}}
```

Or alternatively you can pass it as a query parameter. Like so:
_/any/path/that/needs/authorization?token={{TheAuthTokenReceivedFromTheAuthenticationProcess}}_

PS.

If you are interested in a great tool to test your REST endpoints make sure check out https://www.getpostman.com. In the latest version of the phalcon-rest library I've written a class that generates collections based on the annotations in the controllers you can easily import in Postman. Example: phalcon-rest-boilerplate/app/controllers/ProductController.php
