### ISSUE TITLE
I have some questions...

### ISSUE THREAD

**Issue by Thyoity** [redound/phalcon-rest-boilerplate#7]
First of all, thank you. You did an amazing work here. I didn't install the project yet, but apparently this is very well structured.

I have some questions:
1. Is this project ready for production?
2. How is the authentication working? I tried to follow your code through every single file, but I don't understand how your authentication is working, I can't find anything related to tokens in your schema.sql, or something that could storage any authentication information when the user makes requests.
3. What is that "whitelist" in model files?
4. Is search functions implemented? orders, limits... Is this part of that Fractal package?
5. I have seen something about ACL in your code, this is a great feature. I would like to use it, but I already modeled my database with my own ACL relations, do you think I can make it work with your ACL easily? I know this is a relative question (it depends on my experience in programming), but I just wanted to hear something from you, haha.
6. This is not a question, just: I would like to see a better documentation of your project. For now, this is the only thing I'm missing in your project.

But again, thank you for sharing your project with us, this will be very helpful for most of my projects!

**Comment by andevsoftware** [comment]
@Thyoity, Thanks, glad you like it. 

**Is this project ready for production?**
Yes, I've used the code for production applications already.

**How is the authentication working? I tried to follow your code through every single file, but I don't understand how your authentication is working, I can't find anything related to tokens in your schema.sql, or something that could storage any authentication information when the user makes requests.**
Basically the flow is as follows.
- POST - http:/api.phalcon-rest-boilerplate.dev/users/authenticate/username (depending on the account type you want to authenticate with) with Authorization header ("Authorization": "'Basic sd9u19221934y='") The value after Basic is a base64 encoded string containing "username:password". Note: You can also send { "rememberMe": true } in the request body which will extend the session for a longer period.
- This authorization request either responds with an error or an object containing session info:

``` json
{
  "data": {
    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ1c2VybmFtZSIsInN1YiI6IjEiLCJpYXQiOjE0NDk3NTY4MDAsImV4cCI6MjkwMDExODQwMH0.FE8VYcuh68fxqH17AjILWgcIrOkDp9Q6fBPneD_W4Rc",
    "startTime": 1449756800,
    "expirationTime": 1450361600,
    "user": {
      "id": 1,
      "firstName": "Olivier",
      "lastName": "Andriessen",
      "username": "olivier"
    }
  }
}
```
- After you successfully obtained that token (JSON web token, http://jwt.io/) you can make succeeding requests as follows:
  GET - http://api.phalcon-rest-boilerplate.dev/users/me and send { "Authorization": "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ1c2VybmFtZSIsInN1YiI6IjEiLCJpYXQiOjE0NDk3NTY3OTIsImV4cCI6MjkwMDExODM4NH0.jODd6pWdRgbHqFySE4VE3Crj617XuKMbak_1OJBZml8" } along. Where the long string is the token. If you don't want to user headers for this you can also send the token along with the url as query-parameter like so: (http://api.phalcon-rest-boilerplate.dev/users/me?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ1c2VybmFtZSIsInN1YiI6IjEiLCJpYXQiOjE0NDk3NTY3OTIsImV4cCI6MjkwMDExODM4NH0.jODd6pWdRgbHqFySE4VE3Crj617XuKMbak_1OJBZml8. Note: This is only needed for privateEndpoints (see: https://github.com/olivierandriessen/phalcon-rest-boilerplate/blob/master/app/configs/default.template.php)  

**What is that "whitelist" in model files?**
This array is used for the assign method on models (https://docs.phalconphp.com/en/latest/api/Phalcon_Mvc_Model.html look at assign)

**Is search functions implemented? orders, limits... Is this part of that Fractal package?**
Nope, this may be added in the future. The aim of the library is mainly to give you the structure already, so you can focus on the implementation of these things. Note that you can extend from the classes in the PhalconRest library. You could for instance extend from https://github.com/olivierandriessen/phalcon-rest/blob/master/src/PhalconRest/Http/Request.php and add your own methods to access search queries and so forth. You could always do a pull-request so it could be added to the library if it's useful. I believe Fractal does support a few more things besides response formatting, you have to look into that.  

**I have seen something about ACL in your code, this is a great feature. I would like to use it, but I already modeled my database with my own ACL relations, do you think I can make it work with your ACL easily? I know this is a relative question (it depends on my experience in programming), but I just wanted to hear something from you, haha.**
Sure, I would recommend you look into (https://github.com/olivierandriessen/phalcon-rest-boilerplate/blob/master/app/bootstrap/middleware.php) and just replace it with your own ACL class. It's completely decoupled so it should be just that ;) The boilerplate is there to get you started.

**This is not a question, just: I would like to see a better documentation of your project. For now, this is the only thing I'm missing in your project.**
This is something I really want to do but am in lack of time for. Your not the first one to ask so I will definitely look into it when I have the time. Also, don't hesitate to contribute. Some documentation is surely better than nothing. 

If you have further questions, feedback or want to help you can contact me using mail or Skype.

Good luck!

PS. Checkout http://olivierandriessen.com/getting-started-with-phalcon-rest/ in order to setup the boilerplate.

**Comment by Thyoity** [comment]
First, thank you for your reply.

About the authentication, will the token expirity time update every time I make a request? Or it has a fixed expirity time?

Where is the best place to store this token, in a browser session? (for webapps). In Android, I was thinking of storing in the SharedPreferences (Local storage).

I'm going test this project right now!
If I have further questions, I'll contact you again.

Cheers.

**Comment by andevsoftware** [comment]
@Thyoity It has a fixed expire time. You can use the expirationTime to refresh the session by authenticating again. Personally I stored the session info in localStorage for webapps. I think your approach for Android will be good.

Let me know how it goes ;)

**Comment by Thyoity** [comment]
Thanks for the reply. I'm studying your project right now.
