### ISSUE TITLE
Some new questions.

### ISSUE THREAD

**Issue by Thyoity** [redound/phalcon-rest-boilerplate#9]
Hi! It's me again, hahaha.
I don't know how to use the search feature, how can I implement this feature in a controller (for example, in the ProductController of this boilerplate project)?
Also, is there a way to easily change the name of the "users" table without having to change the library itself? I would like to use the table in singular ("user" instead of "users"), and I want to use email field, instead of username.
Thank you for your help. I already read all from the new documentation. It's way better than before!

**Comment by andevsoftware** [comment]
@Thyoity Hi, 

**Different table names**
Phalcon REST doesn't require you to use models, you can simply [create a new AccountType](http://www.phalcon-rest.org/docs/concepts/authentication.html#add-account-types) and [register it on the AuthManager instance](http://www.phalcon-rest.org/docs/concepts/authentication.html#authentication-manager). To clarify the working of AccountTypes, when you register a new accountType on the AuthManager you can authenticate using the login method and the name of the accountType you just registered. When you call the login method on the authManager it will find your registered accountType based on the name you have registered it with. Then it will call the login method on your accountType using the `$loginData`. You are completely free what you do in this method. You don't even have to use a mysql database, it can be anything. As long as you `return null` when the login failed in any way. In case the login succeeded you return the identity. Because you return a identity the authManager will instantiate a session and store this identity in it. This allows you to later ask the authManager if there has been any session set, obtain the identity, fetch the user/company/identity/whatever you want based on that identity (i would recommend the userId in case it's a user).

``` php
/** @var \PhalconRest\Auth\Manager $authManager */
$authManager = $this->di->get(AppServices::AUTH_MANAGER);

$loginData = ['test@example.com', 'test123'];

/** @var \PhalconRest\Auth\Session $session */
$session = $authManager->login('email', $loginData);
```

**Implementing search**
If you use the UrlQueryMiddleware a global instance of query will be filled with different query options based on the query parameters you pass to the url, for search you could use _[where is like syntax](http://www.phalcon-rest.org/docs/concepts/url-query-syntax.html#where)_:

```
http://phalcon-rest-boilerplate.dev/items?where={"title":{"l":"Samsung"}}
```

If you haven't used the resource concept, and you just want to translate the url query to a phql query you could do the following or see [Using parsed Query](http://www.phalcon-rest.org/docs/concepts/url-query-syntax.html#using-parsed-query):

``` php
$this->query->setModel('App\Model\Product');

/** @var \PhalconRest\Data\Query $query */
$query = $this->get(AppServices::QUERY);

/** @var \PhalconRest\Data\Query\Parser\Phql $phqlQueryParser */
$phqlQueryParser = $this->get(AppServices::PHQL_QUERY_PARSER);

/** @var \Phalcon\Mvc\Model\Query\Builder $phqlBuilder */
$phqlBuilder = $phqlQueryParser->fromQuery($query);

// Resultset
$results = $phqlBuilder->getQuery()->execute();
```

In the following weeks a lot of features will be released including more advanced access control using roles and standard crud resources.
